"""create_tenant_settings_table

Revision ID: 6edffb133c83
Revises: 0dd8ab1a317b
Create Date: 2025-09-01 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edffb133c83'
down_revision: Union[str, Sequence[str], None] = '0dd8ab1a317b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create tenant_settings table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.String(length=36), nullable=False),
        sa.Column('primary_color', sa.String(length=7), nullable=True),
        sa.Column('secondary_color', sa.String(length=7), nullable=True),
        sa.Column('company_logo_url', sa.String(length=1000), nullable=True),
        sa.Column('hover_text', sa.String(length=255), nullable=True),
        sa.Column('welcome_message', sa.Text(), nullable=True),
        sa.Column('chat_window_title', sa.String(length=100), nullable=True),
        sa.Column('additional_settings', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_settings_id'), 'tenant_settings', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    op.create_foreign_key('fk_tenant_settings_tenant_id', 'tenant_settings', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - drop tenant_settings table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenant_settings_tenant_id', 'tenant_settings', type_='foreignkey')
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_index(op.f('ix_tenant_settings_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###