"""add_company_logo_object_name_field

Revision ID: 8c7af17afd5f
Revises: 6edffb133c83
Create Date: 2025-09-01 20:13:53.353205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7af17afd5f'
down_revision: Union[str, Sequence[str], None] = '6edffb133c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_settings', sa.Column('company_logo_object_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'company_logo_object_name')
    # ### end Alembic commands ###
