server:
  port: 8080

logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %yellow([%t]) %blue(%-5level) %magenta(%logger{36}) - %msg%n"
  level:
    org.springframework.web: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: gateway-service
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      # Reactive Spring Cloud Gateway configuration
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - https://app.chatcraft.cc
                  - https://factorai-370af.web.app
                allowedMethods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
                allowedHeaders: "*"
                exposedHeaders: "Authorization, Content-Type, Cache-Control, X-Requested-With, x-request-id, Location, Content-Disposition"
                allowCredentials: true
            add-to-simple-url-handler-mapping: true
          routes:
            # Onboarding Service Routes
            - id: onboarding-documents
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/documents/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: onboarding-categorization
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/categories/**,/api/v1/tags/**,/api/v1/analytics/**,/api/v1/setup/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: onboarding-logo
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/settings-logo/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: auth-tenants
              uri: http://authorization-service:9000
              predicates:
                - Path=/api/v1/tenants/**
              filters:
                - RewritePath=/api/v1/tenants/(?<segment>.*),/auth/api/v1/tenants/$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Expose-Headers

            - id: auth-users
              uri: http://authorization-service:9000
              predicates:
                - Path=/api/v1/users/**
              filters:
                - RewritePath=/api/v1/users/(?<segment>.*),/auth/api/v1/users/$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Expose-Headers

            - id: onboarding-websites
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/websites/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: onboarding-ingestions
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/ingestions/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,



            - id: onboarding-plans
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/plans/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: onboarding-subscriptions
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/subscriptions/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: onboarding-payments
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: onboarding-widgets
              uri: http://onboarding-service:8000
              predicates:
                - Path=/api/v1/widget/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

              # Chat Service Routes
            - id: chat-api
              uri: http://chat-service:8000
              predicates:
                - Path=/api/v1/chat/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            # Communications Service Routes
            - id: communications-email
              uri: http://communications-service:8000
              predicates:
                - Path=/api/v1/email/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: communications-sms
              uri: http://communications-service:8000
              predicates:
                - Path=/api/v1/sms/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: communications-whatsapp
              uri: http://communications-service:8000
              predicates:
                - Path=/api/v1/whatsapp/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: communications-templates
              uri: http://communications-service:8000
              predicates:
                - Path=/api/v1/templates/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: communications-notifications
              uri: http://communications-service:8000
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            # Workflow Service Routes
            - id: workflow-api
              uri: http://workflow-service:8000
              predicates:
                - Path=/api/v1/workflows/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: workflow-executions
              uri: http://workflow-service:8000
              predicates:
                - Path=/api/v1/executions/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            - id: workflow-triggers
              uri: http://workflow-service:8000
              predicates:
                - Path=/api/v1/triggers/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,

            # Auth Service Routes
            - id: auth-api
              uri: http://authorization-service:9000
              predicates:
                - Path=/auth/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Expose-Headers

              # Health Check Routes
            - id: onboarding-health
              uri: http://onboarding-service:8000
              predicates:
                - Path=/health/onboarding
              filters:
                - RewritePath=/health/onboarding,/health

            - id: chat-health
              uri: http://chat-service:8000
              predicates:
                - Path=/health/chat
              filters:
                - RewritePath=/health/chat,/health

            - id: communications-health
              uri: http://communications-service:8000
              predicates:
                - Path=/health/communications
              filters:
                - RewritePath=/health/communications,/health

            - id: workflow-health
              uri: http://workflow-service:8000
              predicates:
                - Path=/health/workflow
              filters:
                - RewritePath=/health/workflow,/health