"""Create initial workflow tables

Revision ID: 2a45ef8b095f
Revises: 
Create Date: 2025-09-27 14:44:12.228579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a45ef8b095f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=255), nullable=False),
    sa.Column('step_type', sa.Enum('MESSAGE', 'CHOICE', 'INPUT', 'CONDITION', 'ACTION', 'SUB_WORKFLOW', 'DELAY', name='steptype'), nullable=False),
    sa.Column('step_config', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_executions_execution_id'), 'step_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_step_executions_id'), 'step_executions', ['id'], unique=False)
    op.create_index(op.f('ix_step_executions_tenant_id'), 'step_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_step_executions_workflow_id'), 'step_executions', ['workflow_id'], unique=False)
    op.create_table('workflow_analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=True),
    sa.Column('completed_executions', sa.Integer(), nullable=True),
    sa.Column('failed_executions', sa.Integer(), nullable=True),
    sa.Column('avg_completion_time_ms', sa.Integer(), nullable=True),
    sa.Column('avg_steps_completed', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('unique_users', sa.Integer(), nullable=True),
    sa.Column('returning_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_analytics_id'), 'workflow_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_analytics_tenant_id'), 'workflow_analytics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_analytics_workflow_id'), 'workflow_analytics', ['workflow_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', 'CANCELLED', name='executionstatus'), nullable=True),
    sa.Column('current_step_id', sa.String(length=255), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_session_id'), 'workflow_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('workflow_states',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('current_step_id', sa.String(length=255), nullable=False),
    sa.Column('step_context', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('waiting_for_input', sa.String(length=100), nullable=True),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('last_bot_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_workflow_states_execution_id'), 'workflow_states', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_session_id'), 'workflow_states', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_tenant_id'), 'workflow_states', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_workflow_id'), 'workflow_states', ['workflow_id'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('default_config', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_id'), 'workflow_versions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_tenant_id'), 'workflow_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='workflowstatus'), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('trigger_type', sa.Enum('MESSAGE', 'INTENT', 'KEYWORD', 'MANUAL', name='triggertype'), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_tenant_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_workflow_states_workflow_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_tenant_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_session_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_execution_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_session_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflow_analytics_workflow_id'), table_name='workflow_analytics')
    op.drop_index(op.f('ix_workflow_analytics_tenant_id'), table_name='workflow_analytics')
    op.drop_index(op.f('ix_workflow_analytics_id'), table_name='workflow_analytics')
    op.drop_table('workflow_analytics')
    op.drop_index(op.f('ix_step_executions_workflow_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_tenant_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_execution_id'), table_name='step_executions')
    op.drop_table('step_executions')
    # ### end Alembic commands ###