"""initial observability models

Revision ID: 9e89bf09a7fc
Revises: 
Create Date: 2026-03-20 17:07:40.540772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e89bf09a7fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observability_backends',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('backend_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'backend_type', name='uq_tenant_backend_type')
    )
    op.create_index(op.f('ix_observability_backends_id'), 'observability_backends', ['id'], unique=False)
    op.create_index(op.f('ix_observability_backends_tenant_id'), 'observability_backends', ['tenant_id'], unique=False)
    op.create_table('observation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('chat_session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_sessions_id'), 'observation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_observation_sessions_tenant_id'), 'observation_sessions', ['tenant_id'], unique=False)
    op.create_table('observation_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['observation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_queries_id'), 'observation_queries', ['id'], unique=False)
    op.create_index(op.f('ix_observation_queries_session_id'), 'observation_queries', ['session_id'], unique=False)
    op.create_index(op.f('ix_observation_queries_tenant_id'), 'observation_queries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_queries_tenant_id'), table_name='observation_queries')
    op.drop_index(op.f('ix_observation_queries_session_id'), table_name='observation_queries')
    op.drop_index(op.f('ix_observation_queries_id'), table_name='observation_queries')
    op.drop_table('observation_queries')
    op.drop_index(op.f('ix_observation_sessions_tenant_id'), table_name='observation_sessions')
    op.drop_index(op.f('ix_observation_sessions_id'), table_name='observation_sessions')
    op.drop_table('observation_sessions')
    op.drop_index(op.f('ix_observability_backends_tenant_id'), table_name='observability_backends')
    op.drop_index(op.f('ix_observability_backends_id'), table_name='observability_backends')
    op.drop_table('observability_backends')
    # ### end Alembic commands ###
