server:
  port: 9002
  servlet:
    context-path: /auth

spring:
  application:
    name: authorization-server

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password


  data:
    redis:
      host: localhost
      port: 6379
      username:
      password:

  cache:
    type: redis
    redis:
      time-to-live: 60000

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authorization_db
    username: postgres
    password: password

authorization:
  config:
    rabbitmq:
      exchange:
        name: topic-exchange
    security:
        allowed-origins:
          - http://localhost:4200
          - https://jwt.io
        location: http://localhost:9002/auth
