server:
  port: 9002
  servlet:
    context-path: /auth

logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %yellow([%t]) %blue(%-5level) %magenta(%logger{36}) - %msg%n"
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2.server.authorization: TRACE
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG

spring:
  application:
    name: authorization-server
  thymeleaf:
    cache: false

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  data:
    redis:
      host: localhost
      port: 6379
      username:
      password:

  cache:
    type: redis
    redis:
      time-to-live: 60000

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authorization_db
    username: postgres
    password: password

authorization:
  config:
    rabbitmq:
      exchange:
        name: topic-exchange
    security:
        allowed-origins:
          - http://localhost:4200
          - https://jwt.io
        location: http://localhost:9002/auth
