"""rename_metadata_columns_to_avoid_sqlalchemy_conflicts

Revision ID: 0dd8ab1a317b
Revises: 5d2d1b6331e1
Create Date: 2025-08-21 16:42:58.322673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd8ab1a317b'
down_revision: Union[str, Sequence[str], None] = '5d2d1b6331e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
