"""create_plans_table_and_update_tenant_plan_reference

Revision ID: 5d2d1b6331e1
Revises: a64897682ecf
Create Date: 2025-08-19 11:24:44.723131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2d1b6331e1'
down_revision: Union[str, Sequence[str], None] = 'a64897682ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_limit', sa.Integer(), nullable=False),
    sa.Column('website_limit', sa.Integer(), nullable=False),
    sa.Column('daily_chat_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_chat_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_plan_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yearly_plan_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.add_column('tenant', sa.Column('plan_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tenant_plan_id'), 'tenant', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'tenant', 'plans', ['plan_id'], ['id'])
    op.drop_column('tenant', 'subscription_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('subscription_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.drop_index(op.f('ix_tenant_plan_id'), table_name='tenant')
    op.drop_column('tenant', 'plan_id')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
