"""Add alert rules, alert history, and job execution logs tables

Revision ID: 17d05ab982ab
Revises: 2ce92ea51ef5
Create Date: 2025-10-20 17:52:43.413806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17d05ab982ab'
down_revision = '2ce92ea51ef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('alert_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_channels_used', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_error', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    op.create_index(op.f('ix_alert_history_rule_id'), 'alert_history', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_tenant_id'), 'alert_history', ['tenant_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('check_interval_hours', sa.Integer(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('notification_channels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_recipients', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('throttle_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('job_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_execution_logs_id'), 'job_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_job_name'), 'job_execution_logs', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_tenant_id'), 'job_execution_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_execution_logs_tenant_id'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_job_name'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_id'), table_name='job_execution_logs')
    op.drop_table('job_execution_logs')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_history_tenant_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_rule_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_table('alert_history')
    # ### end Alembic commands ###
